import logging
import uuid
import time
from functools import lru_cache
from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from app.agent.financial_agent import FinancialAgent
from app.security.rbac import normalize_role


logging.basicConfig(
    level=logging.INFO,
    format=(
        "%(asctime)s | %(levelname)s | "
        "%(name)s | %(message)s"
    ),
)

logger = logging.getLogger(__name__)


class AgentProcessingError(Exception):
    """Raised when the financial agent cannot process a request."""


app = FastAPI(
    title="Financial AI Agent",
    description="AI-powered financial analysis and RAG API",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)



@app.middleware("http")
async def add_request_id(request: Request, call_next):

    request_id = str(uuid.uuid4())

    request.state.request_id = request_id

    start_time = time.perf_counter()

    logger.info(
        "Request started | request_id=%s | method=%s | path=%s",
        request_id,
        request.method,
        request.url.path,
    )

    response = await call_next(request)

    duration_ms = (
        time.perf_counter() - start_time
    ) * 1000

    response.headers["X-Request-ID"] = request_id

    logger.info(
        "Request completed | request_id=%s | "
        "status=%s | duration_ms=%.2f",
        request_id,
        response.status_code,
        duration_ms,
    )

    return response


@app.exception_handler(AgentProcessingError)
async def agent_processing_error_handler(
    request: Request,
    exc: AgentProcessingError,
):

    request_id = getattr(
        request.state,
        "request_id",
        "unknown",
    )

    logger.error(
        "Financial agent processing error | "
        "request_id=%s | error=%s",
        request_id,
        exc,
    )

    return JSONResponse(
        status_code=500,
        content={
            "detail": (
                "An internal error occurred while "
                "processing the question."
            )
        },
    )


@lru_cache
def get_agent():
    """
    Create one shared FinancialAgent instance.
    """

    return FinancialAgent()


class AskRequest(BaseModel):

    question: str = Field(
        ...,
        description="Financial question to analyze.",
    )

    role: str = Field(
        default="CEO",
        description=(
            "User role used for data access control."
        ),
    )


class Source(BaseModel):

    source_file: str

    source_sheet: str | None = None

    source_row: int | None = None


class AskResponse(BaseModel):

    question: str = Field(
        ...,
        description="The original question",
    )

    route: str = Field(
        ...,
        description="The route taken to answer the question",
    )

    answer: str = Field(
        ...,
        description="The answer to the question",
    )

    sources: list[Source] = Field(
        ...,
        description="Sources used to generate the answer",
    )


@app.get("/health")
def health():

    return {
        "status": "healthy",
        "service": "financial-ai-agent",
    }


class FeedbackRequest(BaseModel):
    question: str = Field(..., description="The question that was asked")
    role: str = Field(default="CEO", description="Role of the user")
    rating: int = Field(..., description="+1 for positive, -1 for negative")
    route: str = Field(default="", description="Route taken")
    answer: str = Field(default="", description="Answer generated by agent")
    correction: str = Field(default="", description="Optional user correction")


@app.post("/feedback")
def submit_feedback(body: FeedbackRequest):
    from app.feedback import FeedbackStore
    store = FeedbackStore()
    entry = store.save_feedback(
        question=body.question,
        role=body.role,
        rating=body.rating,
        route=body.route,
        answer=body.answer,
        correction=body.correction,
    )
    return {
        "status": "success",
        "message": "Feedback recorded successfully",
        "entry": entry,
    }


@app.post(
    "/ask",
    response_model=AskResponse,
    summary="Ask a financial question",
    description=(
        "Analyze a financial question using "
        "structured financial data, retrieval-augmented "
        "generation, or a hybrid approach."
    ),
    responses={
        400: {
            "description": "Question cannot be empty.",
        },
        422: {
            "description": "Invalid request format.",
        },
    },
)
def ask(
    request: Request,
    body: AskRequest,
    agent: FinancialAgent = Depends(get_agent),
):

    question = body.question.strip()

    request_id = request.state.request_id

    if not question:

        logger.warning(
            "Empty question | request_id=%s",
            request_id,
        )

        raise HTTPException(
            status_code=400,
            detail="Question cannot be empty.",
        )

    try:
        role = normalize_role(body.role)

    except ValueError:

        logger.warning(
            "Invalid role | request_id=%s | role=%s",
            request_id,
            body.role,
        )

        raise HTTPException(
            status_code=400,
            detail=(
                "Invalid role. Allowed roles: "
                "CEO, CTO, ANALYST."
            ),
        )

    logger.info(
        "Received question | request_id=%s | "
        "role=%s | question=%s",
        request_id,
        role.value,
        question,
    )

    try:

        result = agent.ask(
            question,
            role=role.value,
        )

        logger.info(
            "Question classified | request_id=%s | "
            "role=%s | route=%s",
            request_id,
            role.value,
            result["route"],
        )

        return {
            "question": question,
            "route": result["route"],
            "answer": result["answer"],
            "sources": result.get(
                "sources",
                [],
            ),
        }

    except Exception as exc:

        logger.exception(
            "Error while processing question | "
            "request_id=%s | error=%s",
            request_id,
            exc,
        )

        raise AgentProcessingError(
            "Failed to process financial question."
        ) from exc


from fastapi.staticfiles import StaticFiles

app.mount(
    "/",
    StaticFiles(directory="frontend", html=True),
    name="frontend",
)